### ISSUE TITLE
Flag for review - Deprecation warning in Ember CLI test environment 

### ISSUE THREAD

**Issue by jafarlow** [ember-learn/super-rentals-tutorial#129]
I'm at the end of the Ember Data section in part 2 of the tutorial. We've just built our own adapter to handle the JSON data and I got this warning in the terminal after running the `ember t -s` command:

```
DEPRECATION: store.serializerFor("rental") resolved the "-json-api" serializer via the deprecated `adapter.defaultSerializer` property.

	Previously, if no application or type-specific serializer was specified, the store would attempt to lookup a serializer via the `defaultSerializer` property on the type's adapter. This behavior is deprec favor of explicitly defining a type-specific serializer or application serializer [deprecation id: ember-data:default-serializer] See https://deprecations.emberjs.com/ember-data/v3.x#toc_ember-data:default-seri
alizers for more details.
        at logDeprecationStackTrace (http://localhost:7357/assets/vendor.js:38578:21)
        at HANDLERS.<computed> (http://localhost:7357/assets/vendor.js:38675:9)
        at raiseOnDeprecation (http://localhost:7357/assets/vendor.js:38605:9)
        at HANDLERS.<computed> (http://localhost:7357/assets/vendor.js:38675:9)
        at invoke (http://localhost:7357/assets/vendor.js:38687:9)
        at Object.deprecate (http://localhost:7357/assets/vendor.js:38643:28)
        at DefaultStore.serializerFor (http://localhost:7357/assets/vendor.js:87670:37)
        at http://localhost:7357/assets/vendor.js:84377:30
        at invokeCallback (http://localhost:7357/assets/vendor.js:62786:17)DEPRECATION: store.serializerFor("rental") resolved the "-json-api" serializer via the deprecated `adapter.defaultSerializer` property.

        Previously, if no application or type-specific serializer was specified, the store would attempt to lookup a serializer via the `defaultSerializer` property on the type's adapter. This behavior is deprec favor of explicitly defining a type-specific serializer or application serializer [deprecation id: ember-data:default-serializer] See https://deprecations.emberjs.com/ember-data/v3.x#toc_ember-data:default-seri
alizers for more details.
        at logDeprecationStackTrace (http://localhost:7357/assets/vendor.js:38578:21)
        at HANDLERS.<computed> (http://localhost:7357/assets/vendor.js:38675:9)
        at raiseOnDeprecation (http://localhost:7357/assets/vendor.js:38605:9)
```

All my tests are passing as expected, but the tutorial didn't make mention of this deprecation warning so I thought it should be flagged here. I don't have a suggested fix here, just a flag for someone with experience to review.

**Comment by chancancode** [comment]
Eh good call. We will have to create the adapter/serializer as a pair. Probably need to update the prose a bit too. Thanks for catching it!
